// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Remove quotes if present (common issue with .env files)
const cleanUrl = SUPABASE_URL?.replace(/^["']|["']$/g, '').trim();
const cleanKey = SUPABASE_PUBLISHABLE_KEY?.replace(/^["']|["']$/g, '').trim();

// Validate URL format - must be a valid HTTPS URL and look like a Supabase URL
const isValidUrl = (url: string | undefined): boolean => {
  if (!url || typeof url !== 'string') {
    return false;
  }
  const trimmed = url.trim();
  if (trimmed === '' || trimmed === 'undefined' || trimmed === 'null') {
    return false;
  }
  try {
    const parsed = new URL(trimmed);
    // Must be HTTPS and contain 'supabase' in the domain
    return parsed.protocol === 'https:' && parsed.hostname.includes('supabase');
  } catch {
    return false;
  }
};

// Validate key format - must be a non-empty string
// Supabase keys can be JWT format (starts with eyJ) or other formats
const isValidKey = (key: string | undefined): boolean => {
  if (!key || typeof key !== 'string') {
    return false;
  }
  const trimmed = key.trim();
  return trimmed !== '' && trimmed !== 'undefined' && trimmed !== 'null' && trimmed.length > 10;
};

// Check if Supabase is configured with valid values
export const isSupabaseConfigured = isValidUrl(cleanUrl) && isValidKey(cleanKey);

// Debug logging
if (import.meta.env.DEV) {
  console.log('🔍 Supabase Configuration Check:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    urlValid: isValidUrl(cleanUrl),
    keyValid: isValidKey(cleanKey),
    isConfigured: isSupabaseConfigured,
    urlPreview: cleanUrl ? `${cleanUrl.substring(0, 30)}...` : 'missing',
    keyPreview: cleanKey ? `${cleanKey.substring(0, 20)}...` : 'missing',
  });
}

if (!isSupabaseConfigured) {
  console.warn('⚠️ Supabase is not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.');
  console.warn('The app will use fallback static data for questions.');
  if (cleanUrl && !isValidUrl(cleanUrl)) {
    console.error('❌ Invalid Supabase URL format:', cleanUrl);
  }
  if (cleanKey && !isValidKey(cleanKey)) {
    console.error('❌ Invalid Supabase key format');
  }
}

// Create a minimal mock client when Supabase is not configured
// This uses a valid Supabase URL format to pass validation, but won't actually work
const createMockClient = (): SupabaseClient<Database> => {
  // Use a valid Supabase project URL format that will pass validation
  // Format: https://[project-ref].supabase.co
  // This is a dummy project that won't actually connect
  const mockUrl = 'https://xxxxxxxxxxxxxxxxxxxxx.supabase.co';
  // Use a valid JWT format key (this is a dummy key that won't work)
  const mockKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0';

  try {
    return createClient<Database>(mockUrl, mockKey, {
      auth: {
        storage: {
          getItem: () => null,
          setItem: () => { },
          removeItem: () => { },
        },
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  } catch (error) {
    // If even the mock client fails, log and return a minimal proxy
    console.warn('⚠️ Could not create mock Supabase client. Some features may not work without proper Supabase configuration.');
    // Return a minimal object that matches the SupabaseClient interface
    // This will cause errors if methods are called, but prevents the app from crashing on load
    return {} as SupabaseClient<Database>;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(cleanUrl!, cleanKey!, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : createMockClient();